### ISSUE TITLE
PHP 8.0 fatal error for unknown named parameter $is_singular

### ISSUE THREAD

**Issue by jonathanstegall** [Automattic/ad-code-manager#161]
I've installed PHP 8.0 in preparation for WordPress VIP Go to [begin running it](https://lobby.vip.wordpress.com/2022/05/02/php-8-0-available-on-wordpress-vip/). When I run WordPress (at wp-admin/), I get the following in my error logs:

```php
[02-May-2022 15:19:35 UTC] PHP Fatal error:  Uncaught Error: Unknown named parameter $is_singular in /Users/jonathanstegall/Sites/minnpost-wordpress/wp-content/plugins/ad-code-manager/src/class-ad-code-manager.php:923
Stack trace:
#0 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-content/plugins/ad-code-manager/src/class-ad-code-manager.php(762): Ad_Code_Manager->get_matching_ad_code('dfp_head')
#1 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-content/plugins/ad-code-manager/src/class-ad-code-manager.php(812): Ad_Code_Manager->get_acm_tag('dfp_head')
#2 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/class-wp-hook.php(307): Ad_Code_Manager->action_acm_tag('dfp_head')
#3 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-content/plugins/arcads-dfp-acm-provider/php/class-arcads-dfp-acm-provider-front-end.php(74): do_action('acm_tag', 'dfp_head')
#6 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/class-wp-hook.php(307): ArcAds_DFP_ACM_Provider_Front_End->action_wp_head('')
#7 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#8 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#9 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/general-template.php(3042): do_action('wp_head')
#10 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-content/themes/minnpost-largo/header.php(18): wp_head()
#11 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/template.php(770): require_once('/Users/jonathan...')
#12 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/template.php(716): load_template('/Users/jonathan...', true, Array)
#13 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#14 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-content/themes/minnpost-largo/404.php(10): get_header()
#15 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-includes/template-loader.php(106): include('/Users/jonathan...')
#16 /Users/jonathanstegall/Sites/minnpost-wordpress/wp-blog-header.php(19): require_once('/Users/jonathan...')
#17 /Users/jonathanstegall/Sites/minnpost-wordpress/index.php(17): require('/Users/jonathan...')
#18 /Users/jonathanstegall/.composer/vendor/laravel/valet/server.php(234): require('/Users/jonathan...')
#19 {main}
  thrown in /Users/jonathanstegall/Sites/minnpost-wordpress/wp-content/plugins/ad-code-manager/src/class-ad-code-manager.php on line 923
```

I'm going to do more investigating and see if I can put in a pull request, or if there's anything I can do, but wanted to post since the change seems to be coming up on us pretty quickly.

**Comment by jonathanstegall** [comment]
I'm realizing that this is happening because of my [provider method](https://github.com/MinnPost/arcads-dfp-acm-provider/blob/master/php/class-arcads-dfp-acm-provider-front-end.php#L129-L149) that uses the `acm_conditional_args` filter. I'm not entirely sure why I'm using it this way, it apparently has been like this for several years and I need to look into it further, but here's my method:

```php
public function conditional_args( $args, $function ) {
    global $wp_query;
    // has_category and has_tag use has_term
    // we should pass queried object id for it to produce correct result

    if ( in_array( $function, array( 'has_category', 'has_tag' ) ) ) {
        if ( true === $wp_query->is_single ) {
            $args[] = $wp_query->queried_object->ID;
        }
        $args['is_singular'] = true;
    }
    return $args;
}
```

**Comment by GaryJones** [comment]
Thanks for reporting this @jonathanstegall.

The referenced line is at https://github.com/Automattic/ad-code-manager/blob/322619de4bcc773fa4af772733306c794071acce/src/class-ad-code-manager.php#L923.

This is calling a conditional function, with the args you manipulated. Might be worth var_dumping the `$cond_func` and `$cond_args` (and disable your added filter), and see what the default state is for the conditionals you have set in the UI/database.

**Comment by jonathanstegall** [comment]
Yeah, I'm inclined to think I must've added a line that just doesn't do anything and only now PHP is flagging it. Thanks.
